import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from './lib/api'
import { formatTRY } from './lib/money'

type Summary = { active_jobs:number; due_today:number; overdue:number; ready:number; receivable:string }
type Customer = { id:string; company_name:string; contact_name:string; phone:string; open_balance:string; transactions?: Transaction[] }
type Transaction = { id:string; entry_type:string; direction:string; amount:string; transaction_date:string; description:string }
type Job = { id:string; customer_id:string; customer_name?:string; job_number:string; pattern_name:string; pattern_code:string; quantity:string; unit:string; unit_price:string; total_amount:string; delivery_date:string; status:string }
const statusLabels: Record<string,string> = { yeni:'Yeni', desen_hazirlaniyor:'Desen Hazırlanıyor', onay_bekliyor:'Onay Bekliyor', baskida:'Baskıda', hazir:'Hazır', teslim_edildi:'Teslim Edildi', iptal_edildi:'İptal Edildi' }

function Header({ title, action }: {title:string,action?:React.ReactNode}) { return <header className="page-header"><div><p className="eyebrow">NİZAMLAR ERP</p><h1>{title}</h1></div>{action}</header> }
function ErrorMessage({ error }: {error:string}) { return error ? <p className="error">{error}</p> : null }

export function DashboardPage() { const [data,setData]=useState<Summary>(); const [error,setError]=useState(''); useEffect(()=>{api<Summary>('/dashboard').then(setData).catch((e:Error)=>setError(e.message))},[]); const metrics=data?[['Aktif işler',data.active_jobs,'accent'],['Bugün teslim',data.due_today,'blue'],['Geciken işler',data.overdue,'danger'],['Teslime hazır',data.ready,'success']]:[]; return <><Header title="Günaydın" action={<Link className="button" to="/jobs/new">+ Yeni İş</Link>}/><ErrorMessage error={error}/>{!data?<p className="loading">Ana sayfa yükleniyor…</p>:<><section className="metric-grid">{metrics.map(([label,value,tone])=><article className={`metric ${tone}`} key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="feature-card"><div><p className="eyebrow">FİNANS</p><h2>Müşterilerden alınacak</h2><strong className="amount">{formatTRY(data.receivable)}</strong></div><p>İşler oluşturuldukça müşteri hesap hareketlerinden otomatik hesaplanır.</p></section></>}</> }

export function CustomersPage() { const [customers,setCustomers]=useState<Customer[]>([]); const [search,setSearch]=useState(''); const [error,setError]=useState(''); const load=(q='')=>api<Customer[]>(`/customers?search=${encodeURIComponent(q)}`).then(setCustomers).catch((e:Error)=>setError(e.message)); useEffect(()=>{load()},[]); return <><Header title="Müşteriler" action={<Link className="button" to="/customers/new">+ Müşteri Ekle</Link>}/><div className="toolbar"><input placeholder="Firma adı veya telefon ara" value={search} onChange={e=>{setSearch(e.target.value);load(e.target.value)}}/></div><ErrorMessage error={error}/><section className="list-card">{customers.map(customer=><Link className="list-row" to={`/customers/${customer.id}`} key={customer.id}><div><strong>{customer.company_name}</strong><span>{customer.contact_name||customer.phone||'İletişim bilgisi eklenmemiş'}</span></div><b>{formatTRY(customer.open_balance)}</b></Link>)}{customers.length===0&&!error&&<p className="empty">Henüz müşteri yok. İlk müşterinizi ekleyin.</p>}</section></> }

export function CustomerFormPage() { const navigate=useNavigate(); const [error,setError]=useState(''); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const form=new FormData(e.currentTarget); try { const customer=await api<Customer>('/customers',{method:'POST',body:JSON.stringify(Object.fromEntries(form))}); navigate(`/customers/${customer.id}`) }catch(err){setError((err as Error).message)}}; return <><Header title="Yeni Müşteri"/><form className="form-card" onSubmit={submit}><label>Firma adı<input required name="company_name" autoFocus /></label><div className="two-col"><label>Yetkili<input name="contact_name"/></label><label>Telefon<input name="phone"/></label></div><details><summary>Diğer Bilgiler</summary><label>Adres<textarea name="address"/></label><div className="two-col"><label>Vergi dairesi<input name="tax_office"/></label><label>Vergi numarası<input name="tax_number"/></label></div><label>Not<textarea name="notes"/></label></details><ErrorMessage error={error}/><button className="button" type="submit">Müşteriyi Kaydet</button></form></> }

export function CustomerDetailPage() { const {id=''}=useParams(); const [customer,setCustomer]=useState<Customer>(); const [error,setError]=useState(''); useEffect(()=>{api<Customer>(`/customers/${id}`).then(setCustomer).catch((e:Error)=>setError(e.message))},[id]); if(error)return <><Header title="Müşteri"/><ErrorMessage error={error}/></>; if(!customer)return <p className="loading">Müşteri yükleniyor…</p>; return <><Header title={customer.company_name} action={<Link className="button" to={`/jobs/new?customer=${id}`}>+ Yeni İş</Link>}/><section className="customer-hero"><div><span>Bize borcu</span><strong>{formatTRY(customer.open_balance)}</strong></div><p>{customer.contact_name} {customer.phone&&`· ${customer.phone}`}</p></section><section className="list-card"><h2>Hesap hareketleri</h2>{customer.transactions?.length?customer.transactions.map(t=><div className="list-row" key={t.id}><div><strong>{t.description||t.entry_type}</strong><span>{new Date(t.transaction_date).toLocaleDateString('tr-TR')}</span></div><b>{formatTRY(t.amount)}</b></div>):<p className="empty">Henüz hesap hareketi yok.</p>}</section></> }

export function JobsPage() { const [jobs,setJobs]=useState<Job[]>([]); const [error,setError]=useState(''); useEffect(()=>{api<Job[]>('/jobs').then(setJobs).catch((e:Error)=>setError(e.message))},[]); return <><Header title="İşler" action={<Link className="button" to="/jobs/new">+ Yeni İş</Link>}/><ErrorMessage error={error}/><section className="list-card">{jobs.map(job=><Link className="list-row" to={`/jobs/${job.id}`} key={job.id}><div><strong>{job.job_number} · {job.customer_name}</strong><span>{job.pattern_name||job.pattern_code||'Desen bilgisi yok'} · Teslim {new Date(job.delivery_date).toLocaleDateString('tr-TR')}</span></div><div className="row-right"><em className={`status ${job.status}`}>{statusLabels[job.status]}</em><b>{formatTRY(job.total_amount)}</b></div></Link>)}{jobs.length===0&&!error&&<p className="empty">Henüz iş yok. İlk işi açın.</p>}</section></> }

export function JobFormPage() { const navigate=useNavigate(); const [customers,setCustomers]=useState<Customer[]>([]); const [error,setError]=useState(''); useEffect(()=>{api<Customer[]>('/customers').then(setCustomers).catch((e:Error)=>setError(e.message))},[]); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);try{const job=await api<Job>('/jobs',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});navigate(`/jobs/${job.id}`)}catch(err){setError((err as Error).message)}}; return <><Header title="Yeni İş"/><form className="form-card" onSubmit={submit}><label>Müşteri<select required name="customer_id" defaultValue=""><option value="" disabled>Müşteri seçin</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><div className="two-col"><label>İş / sipariş numarası<input required name="job_number"/></label><label>Desen adı veya kodu<input name="pattern_name"/></label></div><div className="three-col"><label>Kumaş<input name="fabric_info"/></label><label>Baskı türü<input name="print_type"/></label><label>Renk<input name="color_info"/></label></div><div className="three-col"><label>Miktar<input required name="quantity" inputMode="decimal"/></label><label>Birim<select name="unit"><option value="metre">Metre</option><option value="kg">Kg</option><option value="adet">Adet</option></select></label><label>Birim fiyat<input required name="unit_price" inputMode="decimal"/></label></div><div className="two-col"><label>Sipariş tarihi<input required type="date" name="order_date"/></label><label>Teslim tarihi<input required type="date" name="delivery_date"/></label></div><details><summary>Diğer Bilgiler</summary><label>Desen referansı<input name="pattern_reference" placeholder="Dosya adı veya bağlantı"/></label><label>Not<textarea name="notes"/></label></details><ErrorMessage error={error}/><button className="button" type="submit">İşi Kaydet</button></form></> }

export function JobDetailPage() { const {id=''}=useParams(); const [job,setJob]=useState<Job>(); const [error,setError]=useState(''); useEffect(()=>{api<Job>(`/jobs/${id}`).then(setJob).catch((e:Error)=>setError(e.message))},[id]); const change=async(status:string)=>{try{const updated=await api<Job>(`/jobs/${id}/status`,{method:'POST',body:JSON.stringify({status})});setJob(updated)}catch(err){setError((err as Error).message)}}; if(!job)return <p className="loading">İş yükleniyor…</p>; return <><Header title={job.job_number}/><ErrorMessage error={error}/><section className="feature-card"><div><p className="eyebrow">{statusLabels[job.status]}</p><h2>{job.pattern_name||job.pattern_code||'Desen bilgisi yok'}</h2><strong className="amount">{formatTRY(job.total_amount)}</strong></div><div className="status-actions">{['yeni','baskida','hazir','teslim_edildi'].map(s=><button key={s} onClick={()=>change(s)} disabled={job.status===s}>{statusLabels[s]}</button>)}</div></section></> }
